batch_size: 4
iters: 320000

train_dataset:
  type: LaneSegRsa
  dataset_root: /home/work/resa/data/tusimple/
  transforms:
    - type: GroupRandomRotation
    - type: GroupRandomHorizontalFlip
    - type: SampleResize
    - type: GroupNormalize

  mode: train

val_dataset:
  type: LaneSegRsa
  dataset_root: /home/work/resa/data/tusimple
  transforms:
    - type: SampleResize
    - type: GroupNormalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: LaneRsaCrossEntropyLoss
    - type: LaneRsaBCELoss
  coef: [1, 1]

model:
  type: BiSeNetRsa
  pretrained: Null


