batch_size: 4
iters: 320000

train_dataset:
  type: TusimpleSeg
  dataset_root: /home/work/resa/data/tusimple/
  cut_height: 160
  transforms:
    - type: LaneRandomRotation
    - type: RandomHorizontalFlip
    - type: Resize
      target_size: [640, 368]
    - type: Normalize
  mode: train

val_dataset:
  type: TusimpleSeg
  dataset_root: /home/work/resa/data/tusimple/
  cut_height: 160
  transforms:
    - type: Resize
      target_size: [640, 368]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: LaneCrossEntropyLoss
    - type: LaneBCELoss
  coef: [1, 1]

model:
  type: BiSeNetLane
  pretrained: /home/work/PP1109/PaddleSeg/contrib/LaneNet/output11-09-13-01/best_model/model.pdparams


