batch_size: 16
iters: 20000

train_dataset:
  type: LaneSeg
  dataset_root: ./data/tusimple_lane_detection/
  transforms:
    - type: Resize
      target_size: [548, 292]
    - type: RandomDistort
      brightness_range: 0.25
      brightness_prob: 1
      contrast_range: 0.25
      contrast_prob: 1
      saturation_range: 0.25
      saturation_prob: 1
      hue_range: 63
      hue_prob: 1
    - type: RandomHorizontalFlip
    - type: RandomPaddingCrop
      crop_size: [512, 256]
    - type: RandomBlur
      prob: 0.5
      blur_type: random
    - type: RandomNoise
    - type: Normalize

  mode: train

val_dataset:
  type: LaneSeg
  dataset_root: ./data/tusimple_lane_detection/
  transforms:
    - type: Resize
      target_size: [512, 256]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: LaneCrossEntropyLoss
    - type: DiscriminativeLoss
  coef: [1, 1]

model:
  type: LaneBiseNet
  pretrained: Null
